
export const TODO_REQUEST = "TODO_REQUEST";
export const TODO_SUCCESS = "TODO_SUCCESS";
export const TODO_FAILURE = "TODO_FAILURE";

export const GET_TODO_REQUEST = "   GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "   GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "   GET_TODO_FAILURE";