

export const GET_TOODOS_SUCCESS = "GET_TOODOS_SUCCESS"
export const GET_TOODOS_REQUEST = "GET_TOODOS_REQUEST"
export const GET_TOODOS_FAILURE = "GET_TOODOS_FAILURE"
export const ADD_TOODOS_REQUEST = "ADD_TOODOS_REQUEST"
export const ADD_TOODOS_SUCCESS = "ADD_TOODOS_SUCCESS"
export const ADD_TOODOS_FAILURE = "ADD_TOODOS_FAILURE"