
export const GET_TODO_REQUEST = "GET_TODO_REQUEST";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export const DEL_TODO_REQUEST = "DEL_TODO_REQUEST";
export const DEL_TODO_SUCCESS = "DEL_TODO_SUCCESS";
export const DEL_TODO_FAILURE = "DEL_TODO_FAILURE";

export const EDIT_TODO_REQUEST = "EDIT_TODO_REQUEST";
export const EDIT_TODO_SUCCESS = "GEDITTODO_SUCCESS";
export const EDIT_TODO_FAILURE = "GEEDITODO_FAILURE";
